Homeandgamenewverion
facg3/MixTeenApp pull request #50
Opened 2018-01-21 15:36 UTC by ismail2009

### Fixes
fixes #<issue_number>

### Related
related to #<issue_number>

### Summary
A couple of sentences explaining the contents of the PR

### Major Changes
[**OPTIONAL for small PRs**] Detailed description of major changes in the PR, ideally with references to relevant commits, issues, line-numbers, etc.

2018-01-21 15:42 UTC, NadiaKhatib commented on public/js/dom.js
> +  console.log('hghg');
Delete this line console.log('hghg');

2018-01-21 18:27 UTC, Alaa-Khattab approved these changes

2018-01-21 19:07 UTC, marwa7med approved these changes

2018-01-21 19:07 UTC, marwa7med commented on public/css/style.css
> +/*.drag-drop .can-drop {
please remove your comments

2018-01-21 19:07 UTC, marwa7med commented on src/controllers/index.js
> +router.get('/', home.get)
you can write
 module.exports=router
.get('/', home.get)
.get('/levels', levels.get)
.get('/game', game.get);

2018-01-21 19:07 UTC, marwa7med commented on public/js/homeDom.js
> +const navButton = document.querySelector('.burger-btn'); // eslint-disable-line
what is burger-btn 🍔

2018-01-21 19:19 UTC, NadiaKhatib approved these changes

2018-01-21 19:25 UTC, Alaa-Khattab requested changes

2018-01-21 19:25 UTC, Alaa-Khattab commented on public/js/gameDom.js
> +});
why you disabled all these lines ?

2018-01-21 19:25 UTC, marwa7med reviewed
some of these will change

2018-01-21 19:35 UTC, marwa7med reviewed
i  will make some changing here

2018-01-21 19:38 UTC, MarwaBj commented
i show all the changes i'm waiting @ismail2009 to make a change

2018-01-21 19:49 UTC, marwa7med requested changes

2018-01-21 19:49 UTC, MarwaBj commented on src/controllers/index.js
> +router.get('/', home.get)
like @mhmdshorafa  teach us :)

2018-01-22 08:05 UTC, Alaa-Khattab approved these changes

2018-01-22 08:05 UTC, marwa7med approved these changes

2018-01-22 08:06 UTC, merged